name: Build python3-kubernetes Package

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-20.04

    steps:
    - name: Install apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install python3-all debhelper dh-make dh-python apt-file
    - name: Install stdeb
      run: |
        pwd
        STDEB_VERSION="0.10.0"
        wget https://files.pythonhosted.org/packages/13/7e/bd2cfda795d84e4445305cd53c4be4a3ec6fad2546ad2a2b79cc7906b6d7/stdeb-$STDEB_VERSION.tar.gz
        tar xzf stdeb-$STDEB_VERSION.tar.gz
        cd stdeb-$STDEB_VERSION
        python3 setup.py --command-packages=stdeb.command bdist_deb
        sudo dpkg -i ./deb_dist/python3-stdeb_0.10.0-1_all.deb
        sudo apt-get install -f
    - name: Get and Build python3-kubernetes 12.0.1
      run: |
        pwd
        PYKUBE_VERSION="12.0.1"
        wget https://files.pythonhosted.org/packages/a1/56/fd57e391f60dc143402e45560ca87df1d74ddade5ac9b7e9f2cc0338171e/kubernetes-$PYKUBE_VERSION.tar.gz
        tar xzvf kubernetes-$PYKUBE_VERSION.tar.gz
        cd kubernetes-$PYKUBE_VERSION
        python3 setup.py --command-packages=stdeb.command bdist_deb
    - name: Publish package
      uses: actions/upload-artifact@v3
      with:
        name: python3-kubernetes
        path: kubernetes*/deb_dist/*.deb
